version: '3.3'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017

  node-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nodejs
    restart: unless-stopped
    networks:
      app-network:
        ipv4_address: 10.5.0.5
    env_file:
      - .env
    environment:
      MONGO_HOSTNAME: mongodb
    volumes:
      - ./backend:/backend
      - node_modules:/backend/node_modules
    ports:
      - 3000:3000
    command: ./wait-for.sh mongodb:27017 -- node server.js

  angular-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular
    restart: unless-stopped
    networks:
      - app-network
    environment:
      NODE_BACKEND_HOSTNAME: node-backend
    ports:
      - 80:80

networks:
  app-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

volumes:
  dbdata:
  node_modules:
