version: '3.3'

services:
  mongodb:
    image: mongo:4.4.11-rc0
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017

  node-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nodejs
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env
    environment:
      MONGO_HOSTNAME: mongodb
    volumes:
      - ./backend:/backend
      - node_modules:/backend/node_modules
    ports:
      - 3000:3000
    command: ./wait-for.sh mongodb:27017 -- node server.js

  angular-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - 80:80

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
