name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setup
      run: npm ci

    - name: Test
      run: |
        npm test -- --no-watch --no-progress --browsers=ChromeHeadless
        
    - name: Unit Test Report ${{ matrix.node-version }}
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Unit test reports ${{ matrix.node-version }}
        path: /home/runner/work/MEAN-stack/MEAN-stack/junit_report/TESTS-*.xml
        reporter: java-junit
